mod try_avif_heic;
mod try_bmp;
mod try_cur_ico;
mod try_dds;
mod try_gif;
mod try_hdr;
mod try_icns;
mod try_jp2_jpx;
mod try_jpg;
mod try_ktx;
mod try_png;
mod try_psd;
mod try_qoi;
mod try_tiff;
mod try_webp;
mod try_tga;

pub use try_avif_heic::try_avif_heic;
pub use try_bmp::try_bmp;
pub use try_cur_ico::try_cur_ico;
pub use try_dds::try_dds;
pub use try_gif::try_gif;
pub use try_hdr::try_hdr;
pub use try_icns::try_icns;
pub use try_jp2_jpx::try_jp2_jpx;
pub use try_jpg::try_jpg;
pub use try_ktx::try_ktx;
pub use try_png::try_png;
pub use try_psd::try_psd;
pub use try_qoi::try_qoi;
pub use try_tiff::try_tiff;
pub use try_webp::try_webp;
pub use try_tga::try_tga;
