name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Check code style
        run: |
          cargo fmt --all --check

  build:
    needs: code-style
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform:
          - ubuntu-24.04
          - ubuntu-22.04
          - macos-14
          - macos-15
          - windows-2022
          - windows-2025
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Build
        run: |
          cargo test
