name: publish

on:
    create:
        tags:
            - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
    code-style:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    submodules: recursive
            -   name: Check code style
                run: |
                    cargo fmt --all --check

    publish:
        needs: code-style
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    submodules: recursive
            -   name: Publish
                run: |
                    cargo publish --token "${{ secrets.CRATES_IO_TOKEN }}"
