name: publish

on:
  create:
    tags:
      - v*

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      -   name: Checkout
          uses: actions/checkout@v4
          with:
            submodules: recursive
      -   name: Build
          run: |
            cargo publish --token "${{ secrets.CRATES_IO_TOKEN }}"
